# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rockyUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1601, 1139)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-20, -20, 1621, 951))
        self.bg_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_1.setObjectName("bg_1")
        self.bg_border = QtWidgets.QLabel(self.centralwidget)
        self.bg_border.setGeometry(QtCore.QRect(-10, 10, 1601, 861))
        self.bg_border.setStyleSheet("color:rgb(0,0,0);\n"
"\n"
"background-color:rgb(0,0,0);\n"
"border-color: 20px Solid White;\n"
"border-top-color: rgb(225, 225, 225);\n"
"\n"
"")
        self.bg_border.setText("")
        self.bg_border.setObjectName("bg_border")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1040, 750, 251, 91))
        self.pushButton.setStyleSheet("border-color: rgb(180, 180, 180);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("python/buttons/Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(250, 250))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoRepeatDelay(500)
        self.pushButton.setAutoRepeatInterval(500)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1310, 770, 241, 61))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("python/buttons/Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(250, 250))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(4, 5, 811, 521))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("python/Gui/7LP8.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(20, 540, 331, 381))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("python/Gui/f889323d87ae92dbd5da3b1193708dc3.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(1060, 560, 501, 121))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("python/Gui/401-4014880_technology-borders-clip-art.png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1120, 580, 371, 71))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"color:rgb(255,255,255);\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.Terminal = QtWidgets.QLabel(self.centralwidget)
        self.Terminal.setGeometry(QtCore.QRect(390, 570, 611, 301))
        self.Terminal.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"broder: 50px solid white\n"
"")
        self.Terminal.setText("")
        self.Terminal.setObjectName("Terminal")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(824, 6, 771, 171))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("python/Gui/da6684b4ca28374b52947e35e0d6a25cd962ba77r1-680-383_hq.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(834, 200, 761, 331))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("python/voice/Jarvis_Gui (1).gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bg_1.setText(_translate("MainWindow", "TextLabel"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Time:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
